baseURL = "https://astraytlul.github.io/"
languageCode = "en-us"
title = "Astrayt's Blog"

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = true
    lineNumbersInTable = true
    noClasses = false